# Generated by Django 4.2.5 on 2023-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_room_code_alter_room_guest_can_pause"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="guest_can_pause",
            field=models.BooleanField(default=False),
        ),
    ]
